name: ptcg_scouting
version: "1.0.0"
config-version: 2

profile: ptcg_scouting

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ptcg_scouting:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
